var kal = new KeyActionLib();
kal.addItem("Null",function(){console.log("ACTION -> null");});
kal.addItem("Add_a",function(){console.log("ACTION -> add a");});
kal.addItem("Add_b",function(){console.log("ACTION -> add b");});
kal.addItem("Add_c",function(){console.log("ACTION -> add c");});
kal.addItem("Add_d",function(){console.log("ACTION -> add d");});
kal.addItem("Add_e",function(){console.log("ACTION -> add e");});
kal.addItem("Add_f",function(){console.log("ACTION -> add f");});
kal.addItem("Add_g",function(){console.log("ACTION -> add g");});
kal.addItem("Add_h",function(){console.log("ACTION -> add h");});
kal.addItem("Add_i",function(){console.log("ACTION -> add i");});
kal.addItem("Add_j",function(){console.log("ACTION -> add j");});
kal.addItem("Add_k",function(){console.log("ACTION -> add k");});
kal.addItem("Add_l",function(){console.log("ACTION -> add l");});
kal.addItem("Add_m",function(){console.log("ACTION -> add m");});
kal.addItem("Add_n",function(){console.log("ACTION -> add n");});
kal.addItem("Add_o",function(){console.log("ACTION -> add o");});
kal.addItem("Add_p",function(){console.log("ACTION -> add p");});
kal.addItem("Add_q",function(){console.log("ACTION -> add q");});
kal.addItem("Add_r",function(){console.log("ACTION -> add r");});
kal.addItem("Add_s",function(){console.log("ACTION -> add s");});
kal.addItem("Add_t",function(){console.log("ACTION -> add t");});
kal.addItem("Add_u",function(){console.log("ACTION -> add u");});
kal.addItem("Add_v",function(){console.log("ACTION -> add v");});
kal.addItem("Add_w",function(){console.log("ACTION -> add w");});
kal.addItem("Add_x",function(){console.log("ACTION -> add x");});
kal.addItem("Add_y",function(){console.log("ACTION -> add y");});
kal.addItem("Add_z",function(){console.log("ACTION -> add z");});
kal.addItem("Add_A",function(){console.log("ACTION -> add A");});
kal.addItem("Add_B",function(){console.log("ACTION -> add B");});
kal.addItem("Add_C",function(){console.log("ACTION -> add C");});
kal.addItem("Add_D",function(){console.log("ACTION -> add D");});
kal.addItem("Add_E",function(){console.log("ACTION -> add E");});
kal.addItem("Add_F",function(){console.log("ACTION -> add F");});
kal.addItem("Add_G",function(){console.log("ACTION -> add G");});
kal.addItem("Add_H",function(){console.log("ACTION -> add H");});
kal.addItem("Add_I",function(){console.log("ACTION -> add I");});
kal.addItem("Add_J",function(){console.log("ACTION -> add J");});
kal.addItem("Add_K",function(){console.log("ACTION -> add K");});
kal.addItem("Add_L",function(){console.log("ACTION -> add L");});
kal.addItem("Add_M",function(){console.log("ACTION -> add M");});
kal.addItem("Add_N",function(){console.log("ACTION -> add N");});
kal.addItem("Add_O",function(){console.log("ACTION -> add O");});
kal.addItem("Add_P",function(){console.log("ACTION -> add P");});
kal.addItem("Add_Q",function(){console.log("ACTION -> add Q");});
kal.addItem("Add_R",function(){console.log("ACTION -> add R");});
kal.addItem("Add_S",function(){console.log("ACTION -> add S");});
kal.addItem("Add_T",function(){console.log("ACTION -> add T");});
kal.addItem("Add_U",function(){console.log("ACTION -> add U");});
kal.addItem("Add_V",function(){console.log("ACTION -> add V");});
kal.addItem("Add_W",function(){console.log("ACTION -> add W");});
kal.addItem("Add_X",function(){console.log("ACTION -> add X");});
kal.addItem("Add_Y",function(){console.log("ACTION -> add Y");});
kal.addItem("Add_Z",function(){console.log("ACTION -> add Z");});
kal.addItem("Add_0",function(){console.log("ACTION -> add 0");});
kal.addItem("Add_1",function(){console.log("ACTION -> add 1");});
kal.addItem("Add_2",function(){console.log("ACTION -> add 2");});
kal.addItem("Add_3",function(){console.log("ACTION -> add 3");});
kal.addItem("Add_4",function(){console.log("ACTION -> add 4");});
kal.addItem("Add_5",function(){console.log("ACTION -> add 5");});
kal.addItem("Add_6",function(){console.log("ACTION -> add 6");});
kal.addItem("Add_7",function(){console.log("ACTION -> add 7");});
kal.addItem("Add_8",function(){console.log("ACTION -> add 8");});
kal.addItem("Add_9",function(){console.log("ACTION -> add 9");});
kal.addItem("Add_Space",function(){console.log("ACTION -> add ' '");});
kal.addItem("Add_Dot",function(){console.log("ACTION -> add '.'");});
kal.addItem("Add_Comma",function(){console.log("ACTION -> add ','");});
kal.addItem("Add_Question",function(){console.log("ACTION -> add '?'");});
kal.addItem("Add_Exclamation",function(){console.log("ACTION -> add '!'");});
kal.addItem("Add_Colon",function(){console.log("ACTION -> add ':'");});
kal.addItem("Add_SemiColon",function(){console.log("ACTION -> add ';'");});
kal.addItem("Add_Minus",function(){console.log("ACTION -> add '-'");});
kal.addItem("Add_Underscore",function(){console.log("ACTION -> add '_'");});
kal.addItem("Add_Tilde",function(){console.log("ACTION -> add '~'");});
kal.addItem("Add_DotComma",function(){console.log("ACTION -> add ';'");});
kal.addItem("Add_Slash",function(){console.log("ACTION -> add '/'");});
kal.addItem("Add_BackSlash",function(){console.log("ACTION -> add '\\'");});
kal.addItem("Add_VerticalBar",function(){console.log("ACTION -> add '|'");});
kal.addItem("Add_VerticalBar2",function(){console.log("ACTION -> add '¦'");});
kal.addItem("Add_Quote",function(){console.log("ACTION -> add \"'\"");});
kal.addItem("Add_DoubleQuote",function(){console.log("ACTION -> add '\"'");});
kal.addItem("Add_Plus",function(){console.log("ACTION -> add '+'");});
kal.addItem("Add_Asterisk",function(){console.log("ACTION -> add '*'");});
kal.addItem("Add_Sharp",function(){console.log("ACTION -> add '#'");});
kal.addItem("Add_Ampersand",function(){console.log("ACTION -> add '&'");});
kal.addItem("Add_AT",function(){console.log("ACTION -> add '@'");});
kal.addItem("Add_Percent",function(){console.log("ACTION -> add '%'");});
kal.addItem("Add_Dollar",function(){console.log("ACTION -> add '$'");});
kal.addItem("Add_LessThan",function(){console.log("ACTION -> add '<'");});
kal.addItem("Add_MoreThan",function(){console.log("ACTION -> add '>'");});
kal.addItem("Add_OpenParenthesis",function(){console.log("ACTION -> add '('");});
kal.addItem("Add_CloseParenthesis",function(){console.log("ACTION -> add ')'");});
kal.addItem("Add_OpenBracket",function(){console.log("ACTION -> add '['");});
kal.addItem("Add_CloseBracket",function(){console.log("ACTION -> add ']'");});
kal.addItem("Add_OpenBrace",function(){console.log("ACTION -> add '{'");});
kal.addItem("Add_CloseBrace",function(){console.log("ACTION -> add '}'");});
kal.addItem("Add_BackCarret",function(){console.log("ACTION -> add '`'");});
kal.addItem("Add_FrontCarret",function(){console.log("ACTION -> add '´'");});
kal.addItem("Add_Cirumflex",function(){console.log("ACTION -> add '^'");});
kal.addItem("Add_LineFeed",function(){console.log("ACTION -> add LF (\\n)");});
kal.addItem("Add_CarriageReturn",function(){console.log("ACTION -> add CR (\\r)");});
kal.addItem("Add_CrLf",function(){console.log("ACTION -> add CR and LF (\\r\\n)");});
kal.addItem("Confim",function(){console.log("ACTION -> Confirm");});
kal.addItem("Suppress",function(){console.log("ACTION -> Suppress");});
kal.addItem("Delete",function(){console.log("ACTION -> Delete");});
kal.addItem("Cursor_toUp",function(){console.log("ACTION -> cursor to Up");});
kal.addItem("Cursor_toDown",function(){console.log("ACTION -> cursor to Down");});
kal.addItem("Cursor_toLeft",function(){console.log("ACTION -> cursor to Left");});
kal.addItem("Cursor_toRigth",function(){console.log("ACTION -> cursor to Right");});
kal.addItem("Cursor_toHome",function(){console.log("ACTION -> cursor to Home");});
kal.addItem("Cursor_toEnd",function(){console.log("ACTION -> cursor to End");});
kal.addItem("Page_Up",function(){console.log("ACTION -> Page Up");});
kal.addItem("Page_Down",function(){console.log("ACTION -> Page Down");});
kal.addItem("InsertSwitch",function(){console.log("ACTION -> Insert Switch");});
kal.addItem("Exit",function(){console.log("ACTION -> Exit");});
